export const policyData = [
  {
    id: "P-001",
    title: "国务院关于深入实施“人工智能+”行动的意见",
    agency: "国务院",
    region: "全国",
    publishedAt: "2025-08-26",
    deadline: null,
    status: "有效",
    type: "长期政策",
    industries: ["人工智能", "制造业", "软件服务"],
    scales: ["中小企业", "专精特新", "规上企业", "初创团队"],
    goals: ["人工智能应用", "数字化转型"],
    tags: ["人工智能+", "智能体", "算力", "场景开放"],
    summary: "部署人工智能与产业发展等重点领域深度融合，提出强化应用场景、数据、算力、人才和财政金融支持。",
    support: "政策导向、场景开放、财政金融与基础设施支持",
    evidence: ["人工智能与产业发展深度融合", "强化算力、数据与应用场景", "加大财政金融支持"],
    source: "https://www.gov.cn/zhengce/content/202508/content_7037861.htm",
    sourceLabel: "中国政府网"
  },
  {
    id: "P-002",
    title: "中小企业数字化赋能专项行动方案（2025—2027年）",
    agency: "工业和信息化部等部门",
    region: "全国",
    publishedAt: "2024-12-12",
    deadline: "2027-12-31",
    status: "有效",
    type: "行动方案",
    industries: ["制造业", "软件服务", "电子信息"],
    scales: ["中小企业", "专精特新"],
    goals: ["数字化转型", "人工智能应用"],
    tags: ["中小企业", "数字化", "智改数转", "5G工厂"],
    summary: "围绕中小企业数字化转型推进供需对接、场景改造和服务体系建设，鼓励形成小快轻准解决方案。",
    support: "数字化改造、场景示范、公共服务与金融支持",
    evidence: ["优先支持数字化基础较弱的工业中小企业", "打造可复制的数字化场景样本", "鼓励专门信贷与融资担保支持"],
    source: "https://www.miit.gov.cn/jgsj/qyj/wjfb/art/2024/art_7abbb516d2c241b3a04bda0b97711c80.html",
    sourceLabel: "工业和信息化部"
  },
  {
    id: "P-003",
    title: "关于做好2025年中小企业数字化转型城市试点工作的通知",
    agency: "财政部办公厅、工业和信息化部办公厅",
    region: "全国",
    publishedAt: "2025-05-09",
    deadline: "2025-05-20",
    status: "已截止",
    type: "项目申报",
    industries: ["制造业", "电子信息"],
    scales: ["中小企业", "专精特新", "规上企业"],
    goals: ["数字化转型", "人工智能应用", "资金申报"],
    tags: ["城市试点", "专精特新", "工业AI", "场景改造"],
    summary: "推动试点城市聚焦重点行业和重点企业开展深度数字化改造，并推广人工智能在研发、质检和参数优化等场景的应用。",
    support: "城市试点、企业数字化改造与示范推广",
    evidence: ["聚焦制造业重点细分行业", "优先覆盖专精特新与规上工业中小企业", "鼓励人工智能大模型在生产场景落地"],
    source: "https://www.miit.gov.cn/jgsj/qyj/wjfb/art/2025/art_24011c0f91c345339a2813b431356f16.html",
    sourceLabel: "工业和信息化部"
  },
  {
    id: "P-004",
    title: "关于加快推动人工智能赋能制造业高质量发展的若干措施",
    agency: "东莞市人民政府",
    region: "东莞",
    publishedAt: "2025-02-06",
    deadline: null,
    status: "有效",
    type: "产业政策",
    industries: ["人工智能", "制造业", "电子信息", "软件服务"],
    scales: ["中小企业", "专精特新", "规上企业", "初创团队"],
    goals: ["人工智能应用", "数字化转型", "资金申报"],
    tags: ["东莞", "AI+先进制造", "算力", "示范场景"],
    summary: "建设算力与大模型基础设施，支持制造业智能升级、智能产品开发和工业垂直模型应用。",
    support: "算力服务、模型能力、示范场景与产业培育",
    evidence: ["打造AI+先进制造示范应用场景", "支持企业使用智能算力资源", "培育人工智能重点企业"],
    source: "https://www.dg.gov.cn/zwgk/zfxxgkml/smch/zcwj/zcjd/content/post_4336318.html",
    sourceLabel: "东莞市人民政府"
  },
  {
    id: "P-005",
    title: "2026年人工智能赋能新型工业化标杆项目入库预通知",
    agency: "东莞市工业和信息化局",
    region: "东莞",
    publishedAt: "2025-08-07",
    deadline: "2025-08-20",
    status: "已截止",
    type: "项目申报",
    industries: ["人工智能", "制造业", "电子信息"],
    scales: ["中小企业", "专精特新", "规上企业"],
    goals: ["人工智能应用", "资金申报"],
    tags: ["标杆项目", "新型工业化", "项目入库", "广东"],
    summary: "组织符合条件的人工智能赋能新型工业化项目进入省级专项资金项目储备，强调场景成效与示范价值。",
    support: "专项资金项目储备与标杆示范",
    evidence: ["人工智能赋能新型工业化", "面向制造业应用项目", "纳入省级项目储备"],
    source: "https://im.dg.gov.cn/gkmlpt/content/4/4419/post_4419165.html",
    sourceLabel: "东莞市工业和信息化局"
  },
  {
    id: "P-006",
    title: "东莞市支持XR智能终端产业发展的若干措施",
    agency: "东莞市工业和信息化局",
    region: "东莞",
    publishedAt: "2026-01-13",
    deadline: "2029-01-12",
    status: "有效",
    type: "产业政策",
    industries: ["XR", "电子信息", "制造业", "人工智能"],
    scales: ["中小企业", "专精特新", "规上企业", "初创团队"],
    goals: ["人工智能应用", "资金申报", "品牌与质量"],
    tags: ["XR", "智能终端", "电子信息", "产业集群"],
    summary: "推动XR智能终端产业提质上量，支持关键环节突破、品牌培育、园区建设和场景应用。",
    support: "关键技术、产业集群、品牌与应用场景支持",
    evidence: ["聚焦XR关键技术环节", "建设特色产业园区", "培育知名品牌与应用场景"],
    source: "https://www.dg.gov.cn/zjdz/csts/dzys/content/post_4498546.html",
    sourceLabel: "东莞市人民政府"
  },
  {
    id: "P-007",
    title: "关于加强品质提升和品牌打造增创制造业新优势的实施方案（2026—2028年）",
    agency: "东莞市人民政府",
    region: "东莞",
    publishedAt: "2026-02-05",
    deadline: "2028-12-31",
    status: "有效",
    type: "行动方案",
    industries: ["制造业", "电子信息", "XR"],
    scales: ["中小企业", "专精特新", "规上企业"],
    goals: ["品牌与质量", "数字化转型", "人工智能应用"],
    tags: ["品质提升", "品牌打造", "先进制造", "智创优品"],
    summary: "围绕制造业品质、品牌与产业集群能力提升，推动人工智能场景应用与产业带差异化升级。",
    support: "质量提升、品牌培育、产业集群与场景创新",
    evidence: ["提高制造业产品质量水平", "提升自主品牌影响力", "培育质量创新典型案例"],
    source: "https://www.dg.gov.cn/zwgk/zfxxgkml/txz/qt/gzdt/content/post_4498257.html",
    sourceLabel: "东莞市人民政府"
  },
  {
    id: "P-008",
    title: "关于开展2025年专精特新“小巨人”企业认定和复核工作的通知",
    agency: "工业和信息化部办公厅",
    region: "全国",
    publishedAt: "2025-05-14",
    deadline: "2025-06-25",
    status: "已截止",
    type: "资质认定",
    industries: ["制造业", "软件服务", "电子信息"],
    scales: ["专精特新", "中小企业"],
    goals: ["资金申报", "品牌与质量"],
    tags: ["专精特新", "小巨人", "资质认定", "复核"],
    summary: "组织省级专精特新中小企业申报国家级专精特新“小巨人”企业，并开展已认定企业复核。",
    support: "国家级资质认定与梯度培育",
    evidence: ["面向省级专精特新中小企业", "申请与复核不收取费用", "通过优质中小企业梯度培育平台申报"],
    source: "https://www.miit.gov.cn/zwgk/zcwj/wjfb/tz/art/2025/art_fdbc5f469b1e45f589963af5b7955d76.html",
    sourceLabel: "工业和信息化部"
  },
  {
    id: "P-009",
    title: "关于进一步支持专精特新中小企业高质量发展若干政策措施",
    agency: "江苏省人民政府办公厅",
    region: "江苏",
    publishedAt: "2025-04-19",
    deadline: "2028-05-20",
    status: "有效",
    type: "产业政策",
    industries: ["制造业", "软件服务", "电子信息"],
    scales: ["专精特新", "中小企业"],
    goals: ["数字化转型", "品牌与质量", "资金申报"],
    tags: ["专精特新", "数字化转型", "制造强省", "有效期"],
    summary: "从创新能力、数字化转型、质量品牌和融资服务等方面支持专精特新中小企业发展。",
    support: "创新、数字化、质量品牌与融资综合支持",
    evidence: ["支持专精特新中小企业高质量发展", "政策有效期至2028年5月", "覆盖数字化转型与质量品牌"],
    source: "https://www.jiangsu.gov.cn/art/2025/5/9/art_46144_11561210.html",
    sourceLabel: "江苏省人民政府"
  }
];

export const dataMeta = {
  title: "智策雷达政策样本库",
  author: "siuser小伟",
  lastChecked: "2026-08-04",
  policyCount: policyData.length,
  sourceRule: "仅收录政府官方网站或政府公报链接"
};
